;;; compline-theme.el --- Be at peace with the darkness -*- lexical-binding: t; -*-
;;
;; Standalone port of doom-compline.  Doom helper calls (doom-darken,
;; doom-blend) have been resolved to literal hex values.
;;
;; Note: This was slightly clanker written, but I made major edits to the code
;; to better fit the original.
;;
;;; Code:

(deftheme compline
  "Created 2026-10-05.")

(custom-theme-set-faces
 'compline

 ;;;; Core
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1a1d21" :foreground "#f0efeb" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 143 :width normal))))
 '(cursor ((t (:background "#d4ccb4"))))
 '(fixed-pitch ((t (:height 140))))
 '(variable-pitch ((t (:height 140))))
 '(escape-glyph ((t (:foreground "#b4c0c8"))))
 '(homoglyph ((t (:foreground "#b4c0c8"))))
 '(minibuffer-prompt ((t (:foreground "#d4ccb4"))))
 '(highlight ((t (:foreground "#0f1114" :background "#d4ccb4"))))
 '(hl-line ((t (:extend t :background "#22262b"))))
 '(region ((t (:extend t :background "#3d424a"))))
 '(shadow ((t (:foreground "#515761"))))
 '(secondary-selection ((t (:extend t :background "#3d424a"))))
 '(trailing-whitespace ((t (:background "#CDACAC"))))
 '(vertical-border ((t (:foreground "#141619"))))
 '(error ((t (:foreground "#CDACAC"))))
 '(warning ((t (:foreground "#d4ccb4"))))
 '(success ((t (:foreground "#b8c4b8"))))

 ;;;; Line numbers (doom override)
 '(line-number ((t (:foreground "#3d424a"))))
 '(line-number-current-line ((t (:foreground "#f0efeb"))))

 ;;;; Font lock
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#b4c0c8"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#3d424a"))))
 '(font-lock-constant-face ((t (:foreground "#8b919a"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#3d424a" :inherit (font-lock-comment-face)))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:slant italic :foreground "#c6ced2" :inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#b4c0c8"))))
 '(font-lock-keyword-face ((t (:foreground "#e0dcd4"))))
 '(font-lock-negation-char-face ((t (:foreground "#676d77" :inherit (bold)))))
 '(font-lock-number-face ((t (:foreground "#CDACAC"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t (:foreground "#676d77"))))
 '(font-lock-preprocessor-face ((t (:foreground "#676d77" :inherit (bold)))))
 '(font-lock-property-name-face ((t (:weight bold :foreground "#e6e3dd"))))
 '(font-lock-property-use-face ((t (:weight regular :inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#cdcece"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#676d77" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#676d77" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#b8c4b8"))))
 '(font-lock-type-face ((t (:foreground "#b4bcc4"))))
 '(font-lock-variable-name-face ((t (:foreground "#e0dcd4"))))
 '(font-lock-variable-use-face ((t (:foreground "#e8e5df" :inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:inherit (warning)))))

 ;;;; Links, buttons, tooltips
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line :position nil) :foreground "#d4ccb4"))))
 '(link-visited ((t (:inherit link :foreground "#676d77"))))
 '(fringe ((t (:foreground "#3d424a" :inherit (default)))))
 '(tooltip ((t (:foreground "#f0efeb" :background "#22262b"))))

 ;;;; Mode line
 '(header-line ((t (:inherit (mode-line)))))
 '(mode-line ((t (:background "#171a1e" :foreground unspecified))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#d4ccb4"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#4c515a" :background "#202428"))))

 ;;;; Tab bar
 '(tab-bar ((t (:inherit default :background "#1a1d21" :foreground "#676d77"))))
 '(tab-bar-tab ((t (:inherit tab-bar :background "#1f2228" :foreground "#f0efeb" :weight bold :box nil))))
 '(tab-bar-tab-inactive ((t (:inherit tab-bar :background "#1a1d21" :foreground "#ccc4b4" :weight normal :box nil))))

 ;;;; Search
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#0f1114" :background "#CDACAC"))))
 '(lazy-highlight ((t (:weight bold :foreground "#e0dcd4" :background "#948e7e"))))
 '(match ((t (:weight bold :foreground "#b8c4b8" :background "#0f1114"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))

 ;;;; VC gutter: added = green, deleted = red, modified = sand
 '(diff-hl-insert ((t (:foreground "#b8c4b8" :background "#b8c4b8"))))
 '(diff-hl-delete ((t (:foreground "#CDACAC" :background "#CDACAC"))))
 '(diff-hl-change ((t (:foreground "#ccc4b4" :background "#ccc4b4"))))
 '(git-gutter:added ((t (:foreground "#b8c4b8" :background "#b8c4b8"))))
 '(git-gutter:deleted ((t (:foreground "#CDACAC" :background "#CDACAC"))))
 '(git-gutter:modified ((t (:foreground "#ccc4b4" :background "#ccc4b4"))))
 '(git-gutter-fr:added ((t (:foreground "#b8c4b8"))))
 '(git-gutter-fr:deleted ((t (:foreground "#CDACAC"))))
 '(git-gutter-fr:modified ((t (:foreground "#ccc4b4"))))

 ;;;; gnus: group buffer
 '(gnus-group-news-1 ((t (:foreground "#f0efeb" :weight bold))))
 '(gnus-group-news-1-empty ((t (:foreground "#f0efeb" :weight normal))))
 '(gnus-group-news-2 ((t (:foreground "#e0dcd4" :weight bold))))
 '(gnus-group-news-2-empty ((t (:foreground "#e0dcd4" :weight normal))))
 '(gnus-group-news-3 ((t (:foreground "#ccc4b4" :weight bold))))
 '(gnus-group-news-3-empty ((t (:foreground "#ccc4b4" :weight normal))))
 '(gnus-group-news-low ((t (:foreground "#676d77" :weight bold))))
 '(gnus-group-news-low-empty ((t (:foreground "#515761" :weight normal))))
 '(gnus-group-mail-1 ((t (:foreground "#b4bcc4" :weight bold))))
 '(gnus-group-mail-1-empty ((t (:foreground "#b4bcc4" :weight normal))))
 '(gnus-group-mail-2 ((t (:foreground "#b4c0c8" :weight bold))))
 '(gnus-group-mail-2-empty ((t (:foreground "#b4c0c8" :weight normal))))
 '(gnus-group-mail-3 ((t (:foreground "#b4c4bc" :weight bold))))
 '(gnus-group-mail-3-empty ((t (:foreground "#b4c4bc" :weight normal))))
 '(gnus-group-mail-low ((t (:foreground "#676d77" :weight bold))))
 '(gnus-group-mail-low-empty ((t (:foreground "#515761" :weight normal))))

 ;;;; gnus: summary buffer
 '(gnus-summary-normal-unread ((t (:foreground "#f0efeb" :weight bold))))
 '(gnus-summary-normal-read ((t (:foreground "#676d77" :weight normal))))
 '(gnus-summary-normal-ticked ((t (:foreground "#CDACAC" :weight bold))))
 '(gnus-summary-normal-ancient ((t (:foreground "#515761" :weight normal))))
 '(gnus-summary-normal-undownloaded ((t (:foreground "#8b919a" :slant italic))))
 '(gnus-summary-high-unread ((t (:foreground "#d4ccb4" :weight bold))))
 '(gnus-summary-high-read ((t (:foreground "#948e7e" :weight normal))))
 '(gnus-summary-high-ticked ((t (:foreground "#CDACAC" :weight bold))))
 '(gnus-summary-high-ancient ((t (:foreground "#676d77" :weight normal))))
 '(gnus-summary-low-unread ((t (:foreground "#8b919a" :slant italic :weight bold))))
 '(gnus-summary-low-read ((t (:foreground "#515761" :slant italic :weight normal))))
 '(gnus-summary-low-ticked ((t (:foreground "#CDACAC" :slant italic))))
 '(gnus-summary-low-ancient ((t (:foreground "#3d424a" :slant italic))))
 '(gnus-summary-selected ((t (:background "#3d424a" :foreground "#f0efeb" :weight bold))))
 '(gnus-summary-cancelled ((t (:foreground "#CDACAC" :strike-through t))))

 ;;;; gnus: article headers, citations, misc
 '(gnus-header-name ((t (:foreground "#b4bcc4" :weight bold))))
 '(gnus-header-content ((t (:foreground "#ccc4b4" :slant italic))))
 '(gnus-header-from ((t (:foreground "#f0efeb" :weight bold))))
 '(gnus-header-subject ((t (:foreground "#e0dcd4"))))
 '(gnus-header-newsgroups ((t (:foreground "#ccc4b4" :slant italic))))
 '(gnus-cite-1 ((t (:foreground "#b4bcc4"))))
 '(gnus-cite-2 ((t (:foreground "#b8c4b8"))))
 '(gnus-cite-3 ((t (:foreground "#ccc4b4"))))
 '(gnus-cite-4 ((t (:foreground "#CDACAC"))))
 '(gnus-cite-5 ((t (:foreground "#b4c0c8"))))
 '(gnus-cite-6 ((t (:foreground "#b4c4bc"))))
 '(gnus-cite-7 ((t (:foreground "#9ca4ac"))))
 '(gnus-cite-8 ((t (:foreground "#98a4ac"))))
 '(gnus-cite-9 ((t (:foreground "#8b919a"))))
 '(gnus-cite-10 ((t (:foreground "#676d77"))))
 '(gnus-cite-11 ((t (:foreground "#515761"))))
 '(gnus-signature ((t (:foreground "#515761" :slant italic))))
 '(gnus-button ((t (:inherit link))))
 '(gnus-splash ((t (:foreground "#515761"))))
 '(gnus-emphasis-bold ((t (:weight bold))))
 '(gnus-emphasis-italic ((t (:slant italic))))
 '(gnus-emphasis-underline ((t (:underline t))))
 '(gnus-emphasis-bold-italic ((t (:weight bold :slant italic))))
 '(gnus-server-opened ((t (:foreground "#b8c4b8" :weight bold))))
 '(gnus-server-closed ((t (:foreground "#676d77" :slant italic))))
 '(gnus-server-denied ((t (:foreground "#CDACAC" :weight bold))))
 '(gnus-server-offline ((t (:foreground "#ccc4b4" :weight bold))))
 '(gnus-server-agent ((t (:foreground "#b4bcc4" :weight bold))))

 ;;;; message (gnus composition buffers)
 '(message-header-name ((t (:foreground "#b4bcc4" :weight bold))))
 '(message-header-to ((t (:foreground "#f0efeb" :weight bold))))
 '(message-header-cc ((t (:foreground "#e0dcd4"))))
 '(message-header-subject ((t (:foreground "#f0efeb" :weight bold))))
 '(message-header-newsgroups ((t (:foreground "#ccc4b4" :slant italic))))
 '(message-header-other ((t (:foreground "#ccc4b4"))))
 '(message-header-xheader ((t (:foreground "#676d77"))))
 '(message-separator ((t (:foreground "#515761"))))
 '(message-mml ((t (:foreground "#b8c4b8"))))
 '(message-cited-text-1 ((t (:foreground "#b4bcc4"))))
 '(message-cited-text-2 ((t (:foreground "#b8c4b8"))))
 '(message-cited-text-3 ((t (:foreground "#ccc4b4"))))
 '(message-cited-text-4 ((t (:foreground "#CDACAC"))))

 ;;;; magit: sections
 '(magit-section-heading ((t (:foreground "#d4ccb4" :weight bold :extend t))))
 '(magit-section-secondary-heading ((t (:foreground "#8b919a" :weight bold :extend t))))
 '(magit-section-heading-selection ((t (:foreground "#ccc4b4" :weight bold :extend t))))
 '(magit-section-highlight ((t (:background "#22262b" :extend t))))
 '(magit-section-child-count ((t (:foreground "#676d77"))))

 ;;;; magit: refs, hashes, log
 '(magit-branch-local ((t (:foreground "#b4bcc4"))))
 '(magit-branch-remote ((t (:foreground "#b8c4b8"))))
 '(magit-branch-current ((t (:foreground "#b4bcc4" :weight bold :box (:line-width -1 :color "#515761")))))
 '(magit-branch-remote-head ((t (:foreground "#b8c4b8" :weight bold :box (:line-width -1 :color "#515761")))))
 '(magit-branch-upstream ((t (:slant italic))))
 '(magit-tag ((t (:foreground "#ccc4b4"))))
 '(magit-hash ((t (:foreground "#676d77"))))
 '(magit-dimmed ((t (:foreground "#515761"))))
 '(magit-filename ((t (:foreground "#e0dcd4"))))
 '(magit-refname ((t (:foreground "#676d77"))))
 '(magit-refname-stash ((t (:foreground "#676d77"))))
 '(magit-refname-wip ((t (:foreground "#676d77"))))
 '(magit-log-author ((t (:foreground "#ccc4b4"))))
 '(magit-log-date ((t (:foreground "#676d77"))))
 '(magit-log-graph ((t (:foreground "#515761"))))
 '(magit-keyword ((t (:foreground "#ccc4b4"))))
 '(magit-keyword-squash ((t (:foreground "#d4ccb4"))))
 '(magit-cherry-equivalent ((t (:foreground "#f0efeb"))))
 '(magit-cherry-unmatched ((t (:foreground "#b4c0c8"))))

 ;;;; magit: diffs
 '(magit-diff-file-heading ((t (:foreground "#f0efeb" :weight bold :extend t))))
 '(magit-diff-file-heading-highlight ((t (:inherit magit-diff-file-heading :background "#22262b"))))
 '(magit-diff-file-heading-selection ((t (:inherit magit-diff-file-heading :foreground "#ccc4b4" :background "#3d424a"))))
 '(magit-diff-hunk-heading ((t (:foreground "#8b919a" :background "#282c34" :extend t))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#f0efeb" :background "#3d424a" :extend t))))
 '(magit-diff-hunk-heading-selection ((t (:foreground "#ccc4b4" :background "#3d424a" :extend t))))
 '(magit-diff-lines-heading ((t (:foreground "#1a1d21" :background "#ccc4b4" :extend t))))
 '(magit-diff-context ((t (:foreground "#676d77" :extend t))))
 '(magit-diff-context-highlight ((t (:foreground "#8b919a" :background "#22262b" :extend t))))
 '(magit-diff-added ((t (:foreground "#b8c4b8" :background "#232a25" :extend t))))
 '(magit-diff-added-highlight ((t (:foreground "#b8c4b8" :background "#2a342d" :extend t))))
 '(magit-diff-removed ((t (:foreground "#CDACAC" :background "#2b2323" :extend t))))
 '(magit-diff-removed-highlight ((t (:foreground "#CDACAC" :background "#352a2a" :extend t))))
 '(magit-diffstat-added ((t (:foreground "#b8c4b8"))))
 '(magit-diffstat-removed ((t (:foreground "#CDACAC"))))
 '(magit-diff-whitespace-warning ((t (:background "#CDACAC"))))

 ;;;; magit: process, signatures, sequences, blame, header line
 '(magit-process-ok ((t (:foreground "#b8c4b8" :weight bold))))
 '(magit-process-ng ((t (:foreground "#CDACAC" :weight bold))))
 '(magit-mode-line-process ((t (:foreground "#ccc4b4"))))
 '(magit-mode-line-process-error ((t (:foreground "#CDACAC"))))
 '(magit-signature-good ((t (:foreground "#b8c4b8"))))
 '(magit-signature-bad ((t (:foreground "#CDACAC" :weight bold))))
 '(magit-signature-untrusted ((t (:foreground "#b4bcc4"))))
 '(magit-signature-expired ((t (:foreground "#ccc4b4"))))
 '(magit-signature-expired-key ((t (:foreground "#ccc4b4"))))
 '(magit-signature-revoked ((t (:foreground "#CDACAC"))))
 '(magit-signature-error ((t (:foreground "#CDACAC"))))
 '(magit-sequence-head ((t (:foreground "#b4bcc4"))))
 '(magit-sequence-stop ((t (:foreground "#b8c4b8"))))
 '(magit-sequence-part ((t (:foreground "#ccc4b4"))))
 '(magit-sequence-done ((t (:foreground "#676d77"))))
 '(magit-sequence-onto ((t (:foreground "#676d77"))))
 '(magit-bisect-good ((t (:foreground "#b8c4b8"))))
 '(magit-bisect-skip ((t (:foreground "#ccc4b4"))))
 '(magit-bisect-bad ((t (:foreground "#CDACAC"))))
 '(magit-blame-heading ((t (:foreground "#8b919a" :background "#282c34" :extend t))))
 '(magit-header-line ((t (:foreground "#d4ccb4" :weight bold))))
 '(magit-header-line-key ((t (:foreground "#d4ccb4"))))
 '(magit-header-line-log-select ((t (:foreground "#f0efeb" :weight bold))))

 ;;;; transient (magit popups)
 '(transient-heading ((t (:foreground "#d4ccb4" :weight bold))))
 '(transient-key ((t (:foreground "#d4ccb4" :weight bold))))
 '(transient-key-exit ((t (:foreground "#CDACAC" :weight bold))))
 '(transient-key-return ((t (:foreground "#ccc4b4" :weight bold))))
 '(transient-key-stay ((t (:foreground "#b8c4b8" :weight bold))))
 '(transient-argument ((t (:foreground "#b8c4b8" :weight bold))))
 '(transient-value ((t (:foreground "#b8c4b8"))))
 '(transient-inactive-argument ((t (:foreground "#676d77"))))
 '(transient-inactive-value ((t (:foreground "#676d77"))))
 '(transient-unreachable ((t (:foreground "#515761"))))
 '(transient-unreachable-key ((t (:foreground "#515761"))))
 '(transient-disabled-suffix ((t (:foreground "#0f1114" :background "#CDACAC" :weight bold))))
 '(transient-enabled-suffix ((t (:foreground "#0f1114" :background "#b8c4b8" :weight bold))))
 '(transient-delimiter ((t (:foreground "#676d77"))))
 '(transient-separator ((t (:background "#171a1e"))))
 '(transient-active-infix ((t (:foreground "#f0efeb" :background "#3d424a"))))
 '(transient-mismatched-key ((t (:underline t))))
 '(transient-nonstandard-key ((t (:underline t))))

 ;;;; git-commit (magit commit message buffer)
 '(git-commit-summary ((t (:foreground "#f0efeb" :weight bold))))
 '(git-commit-overlong-summary ((t (:foreground "#CDACAC" :weight bold))))
 '(git-commit-nonempty-second-line ((t (:foreground "#CDACAC"))))
 '(git-commit-keyword ((t (:foreground "#b4bcc4"))))
 '(git-commit-comment-heading ((t (:foreground "#ccc4b4" :weight bold))))
 '(git-commit-comment-branch-local ((t (:foreground "#b4bcc4"))))
 '(git-commit-comment-branch-remote ((t (:foreground "#b8c4b8"))))
 '(git-commit-comment-detached ((t (:foreground "#ccc4b4"))))
 '(git-commit-comment-file ((t (:foreground "#ccc4b4"))))
 '(git-commit-comment-action ((t (:foreground "#b8c4b8"))))

 ;;;; erc: buffer text
 '(erc-default-face ((t (:foreground "#f0efeb"))))
 '(erc-input-face ((t (:foreground "#b8c4b8"))))
 '(erc-my-nick-face ((t (:foreground "#b8c4b8" :weight bold))))
 '(erc-my-nick-prefix-face ((t (:foreground "#b8c4b8" :weight bold))))
 '(erc-nick-default-face ((t (:foreground "#f0efeb" :weight bold))))
 '(erc-nick-prefix-face ((t (:foreground "#ccc4b4"))))
 '(erc-notice-face ((t (:foreground "#676d77" :weight normal))))
 '(erc-information ((t (:foreground "#8b919a"))))
 '(erc-timestamp-face ((t (:foreground "#515761" :weight normal))))
 '(erc-action-face ((t (:foreground "#e0dcd4" :weight bold))))
 '(erc-prompt-face ((t (:foreground "#ccc4b4" :weight bold))))
 '(erc-command-indicator-face ((t (:foreground "#8b919a" :weight bold))))
 '(erc-error-face ((t (:foreground "#CDACAC"))))
 '(erc-button ((t (:inherit link :foreground "#f0efeb"))))
 '(erc-button-nick-default-face ((t (:foreground "#f0efeb" :weight bold))))
 '(erc-bold-face ((t (:weight bold))))
 '(erc-italic-face ((t (:slant italic))))
 '(erc-underline-face ((t (:underline t))))
 '(erc-inverse-face ((t (:foreground "#1a1d21" :background "#f0efeb"))))
 '(erc-keep-place-indicator-line ((t (:underline (:color "#515761" :style line)))))
 '(erc-keep-place-indicator-arrow ((t (:foreground "#CDACAC"))))
 '(erc-header-line ((t (:foreground "#8b919a" :background "#171a1e"))))
 '(erc-header-line-disconnected ((t (:foreground "#CDACAC" :background "#171a1e"))))

 ;;;; erc: highlighting rules (these also colour the mode-line channel tracker)
 '(erc-current-nick-face ((t (:foreground "#d4ccb4" :weight bold))))
 '(erc-keyword-face ((t (:foreground "#d4ccb4" :weight bold))))
 '(erc-nick-msg-face ((t (:foreground "#ccc4b4" :weight bold))))
 '(erc-direct-msg-face ((t (:foreground "#CDACAC"))))
 '(erc-pal-face ((t (:foreground "#b8c4b8" :weight bold))))
 '(erc-fool-face ((t (:foreground "#515761"))))
 '(erc-dangerous-host-face ((t (:foreground "#CDACAC"))))

 ;;;; css-mode / scss-mode
 '(css-proprietary-property ((t (:foreground "#ccc4b4"))))
 '(css-property ((t (:foreground "#f0efeb"))))
 '(css-selector ((t (:foreground "#CDACAC"))))

 ;;;; markdown-mode
 '(markdown-markup-face ((t (:foreground "#515761"))))
 '(markdown-header-face ((t (:inherit bold :foreground "#CDACAC"))))
 '(markdown-code-face ((t (:background "#171a1e"))))

 ;;;; outline
 '(outline-1 ((t (:foreground "#f0efeb" :weight ultra-bold))))
 '(outline-2 ((t (:foreground "#c9ced2"))))
 '(outline-3 ((t (:foreground "#dee0df"))))
 '(outline-4 ((t (:foreground "#b4bcc4"))))
 '(outline-5 ((t (:foreground "#acb3bc"))))
 '(outline-6 ((t (:foreground "#a4abb3"))))
 '(outline-7 ((t (:foreground "#9ba2ab"))))
 '(outline-8 ((t (:foreground "#f0efeb"))))

 ;;;; org
 '(org-block ((t (:background "#212529"))))
 '(org-block-begin-line ((t (:foreground "#3d424a" :slant italic :background "#191c20"))))
 '(org-ellipsis ((t (:underline nil :background "#1a1d21" :foreground "#CDACAC"))))
 '(org-quote ((t (:background "#171a1e"))))
 '(org-hide ((t (:foreground "#1a1d21"))))

 ;;;; solaire-mode
 '(solaire-mode-line-face ((t (:inherit mode-line :background "#171a1e"))))
 '(solaire-mode-line-inactive-face ((t (:inherit mode-line-inactive :background "#171a1e")))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'compline)

;;; compline-theme.el ends here
